---
version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto:/mosquitto:rw
    ports:
      - "9001:9001"
      - "1883:1883"
  python:
    build: ./pythonFiles
    volumes:
      - ./pythonFiles:/code:rw
   
